# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 01:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=254)),
                ('line2', models.CharField(blank=True, max_length=254)),
                ('line3', models.CharField(blank=True, max_length=254)),
                ('location_name', models.CharField(blank=True, max_length=254)),
                ('city', models.CharField(max_length=254)),
                ('state', models.CharField(max_length=254)),
                ('postal_code', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocd_id', models.CharField(help_text='Open Civic Data division ID', max_length=254, unique=True)),
                ('name', models.CharField(help_text='Name of political division', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of office', max_length=254)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='meetings.Division')),
            ],
        ),
        migrations.CreateModel(
            name='Official',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('party', models.CharField(max_length=254)),
                ('in_office', models.BooleanField(default=True, help_text='Is this person currently holding office')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officials', to='meetings.Office')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='meetings.Official')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=254)),
                ('channel_type', models.CharField(choices=[('GooglePlus', 'Google +'), ('YouTube', 'YouTube'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter')], max_length=20)),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='meetings.Official')),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='meetings.Official')),
            ],
        ),
        migrations.AddField(
            model_name='email',
            name='official',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='meetings.Official'),
        ),
        migrations.AddField(
            model_name='address',
            name='official',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='meetings.Official'),
        ),
        migrations.CreateModel(
            name='ContactAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email')], max_length=10)),
                ('contacted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_attempts', to='meetings.Official')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='meetings.Official')),
                ('event_website', models.URLField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['ocd_id']},
        ),
        migrations.AddField(
            model_name='official',
            name='meeting_info_source',
            field=models.TextField(blank=True),
        ),
    ]
