# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 15:05
from __future__ import unicode_literals

from django.db import migrations

def set_meeting_type_for_phone_facebook_meetings(apps, schema_editor):
    Meeting = apps.get_model("meetings", "Meeting")
    Meeting.objects.filter(location__icontains="phone")\
        .update(meeting_type='telephone')
    Meeting.objects.filter(location__icontains="facebook")\
        .update(meeting_type='facebook')


def unset_meeting_type_for_phone_facebook_meetings(apps, schema_editor):
    Meeting = apps.get_model("meetings", "Meeting")
    Meeting.objects.filter(location__icontains="phone", meeting_type='telephone')\
        .update(meeting_type=None)
    Meeting.objects.filter(location__icontains="facebook", meeting_type='facebook')\
        .update(meeting_type=None)


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20170418_1451'),
    ]

    operations = [
        migrations.RunPython(set_meeting_type_for_phone_facebook_meetings,
            reverse_code=unset_meeting_type_for_phone_facebook_meetings),
    ]
