# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-30 22:12
from __future__ import unicode_literals

import re

import archieml

from django.db import migrations
from django.utils.text import slugify


def fields_from_notes(meeting):
    normalized = {}
    parsed = archieml.loads(meeting.notes)
    for k, v in parsed.items():
        normalized[slugify(k).replace('-', '_')] = v

    return normalized


def source_urls(meeting):
    fields = fields_from_notes(meeting)

    if 'source' in fields:
        sources = fields['source']

        if not isinstance(sources, list):
            sources = [sources,]

        for source_url in sources:
            yield source_url


def add_sources(apps, schema_editor):
    Meeting = apps.get_model('meetings', 'Meeting')
    Source = apps.get_model('meetings', 'Source')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    for meeting in Meeting.objects.all():
        for url in source_urls(meeting):
            if not re.match(r'http', url):
                continue

            Source.objects.create(
                url=url,
                content_type=ContentType.objects.get_for_model(meeting),
                object_id=meeting.pk
            )


def remove_sources(apps, schema_editor):
    Source = apps.get_model('meetings', 'Source')
    Source.objects.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_auto_20170630_2026'),
    ]

    operations = [
        migrations.RunPython(add_sources, remove_sources),
    ]
